In [11]:
import pandas as pd
import numpy as np
print(f"Pandas version: {pd.__version__}")
# Read dataset file
df_arq1 = pd.read_csv("/home/marcus-vinicius/Desktop/Python/Machine_Leaning_Zoomcamp/car_fuel_efficiency.csv")
# Select all the cars from Asia
asia = df_arq1[df_arq1["origin"] == "Asia"]
print(asia.head())
print("x"*100)
selected_col = asia[["model_year", "vehicle_weight"]]
print(np.array(selected_col.head(7)))
# Underlying Numpy array of the first 7 values of collumns: "vehicle_weight" and "model_year"
X = np.array(selected_col.head(7))
TransposeX = X.T
# Multiplication between the transpose of X and X
XTX = TransposeX@X
XTX_inv = np.linalg.inv(XTX)
# Weight/target of my model
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = (XTX_inv @ TransposeX) @ y
print("{:.2f}".format(w.sum()))

Pandas version: 2.1.4
    engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14  

In [14]:
X = np.array(selected_col.head(7))
print(X)
print("x"*100)
TransposeX = X.T
print(TransposeX)
print("x"*100)
XTX = TransposeX@X
print(XTX)
print("x"*100)
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)
print('x'*100)
w = (XTX_inv @ TransposeX) @ y
print(w)

[[2016.         2714.21930965]
 [2010.         2783.86897424]
 [2007.         3582.68736772]
 [2011.         2231.8081416 ]
 [2016.         2659.43145076]
 [2014.         2844.22753389]
 [2019.         3761.99403819]]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[2016.         2010.         2007.         2011.         2016.
  2014.         2019.        ]
 [2714.21930965 2783.86897424 3582.68736772 2231.8081416  2659.43145076
  2844.22753389 3761.99403819]]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[28373339.         41431216.50732678]
 [41431216.50732678 62248334.33150762]]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[[ 1.25380877e-06 -8.34509443e-07]
 [-8.34509443e-07  5.71497081e-07]]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[0.5049067  0.01386421]
